#!/bin/bash

which go 2>&1  &> /dev/null
if [ $? -gt 0 ]
then
	echo Cannot find go, exiting
	exit 1
fi

testFolder() {
    folderName=$1
    go test ./${folderName}
}

testFolder crypto
testFolder miner/api
testFolder miner/state
testFolder shared/datastruct
